# Ce modèle AWS SAM a été généré à partir de 
# la configuration de votre fonction. Si votre fonction possède un 
# ou plusieurs déclencheurs, notez que les ressources AWS associées à 
# ces déclencheurs ne sont pas entièrement spécifiées dans ce modèle 
# et qu'elles incluent des valeurs d'espace réservé. Ouvrez ce modèle 
# dans AWS Application Composer ou dans votre IDE préféré et modifiez-le pour 
# spécifier une application sans serveur avec d'autres ressources AWS. 
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
  5LAMBuserlogin:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Handler: index.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      EphemeralStorage:
        Size: 512
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /login
            Method: POST
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      SnapStart:
        ApplyOn: None
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:eu-north-1:919514698420:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:eu-north-1:919514698420:log-group:/aws/lambda/5LAMB-user-login:*
